Repository ralixjs/ralix, pull requests merged in 2020-08, with the labels that each got.

#43 serialize function
  docs/CORE_API.md
  src/core.js
Labels: discussion, wip

#42 Reference classes or attributes to select DOM objects
  README.md
  src/core.js
Labels: discussion, enhancement, wip

#45 move private functions _element and _elements implementation to find and findAll
  src/core.js
Labels: engineering
